### ISSUE TITLE
Hide EventSummary when only the settings panel is visible

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-latest-earthquakes#172]
This could be tough to figure out. 

Our z-index currently reflects the layering of the different modes. The list lives on top and is therefore always visible when enabled, this makes it impossible to use z-index to hide the EventSummaryView when only "about" or "settings" is enabled. 

z-index is as follows:
 - header/footer (which contains EventSummary) = 4
 - list = 3
 - settings = 2
 - map = 1
 - about = 0

**Comment by emartinez-usgs** [comment]
The current PR seems to add a lot of unnecessarily heavy rules. Would it not suffice like so:

```css
.event-summary-view {
  display: none;
}

.mode-list,
.mode-map {
  + .latest-earthquakes-footer > .event-summary-view {
    display: block;
  }
}
```
